import './style.css';
import { createIcons, icons } from 'lucide';
import { geoMercator, geoPath, geoArea } from 'd3-geo';
import { feature } from 'topojson-client';
import world from 'world-atlas/countries-110m.json';
import { places, categories, eras } from './data.js';
const $ = s => document.querySelector(s);
const icon = (name,cls='') => `<i data-lucide="${name}" class="${cls}"></i>`;
const refreshIcons = () => createIcons({icons,attrs:{'stroke-width':1.65}});
let stored=[]; try { stored=JSON.parse(localStorage.getItem('kala-saved')||'[]'); } catch {}
const state={category:'all',era:'all',region:'all',search:'',selected:'ajanta',saved:new Set(Array.isArray(stored)?stored:[]),savedOnly:false,view:'map'};
let projection, pan={x:0,y:0},zoom=1,drag=null,moved=false,lastFocus;
const categoryOf = p => categories.find(c=>c.id===p.category);
const filtered = () => places.filter(p=>(state.category==='all'||p.category===state.category)&&(state.era==='all'||p.era.includes(state.era))&&(state.region==='all'||p.region===state.region)&&(!state.savedOnly||state.saved.has(p.id))&&`${p.name} ${p.state} ${p.tradition} ${p.artists}`.toLowerCase().includes(state.search.toLowerCase()));
$('#app').innerHTML=`
<header class="site-header"><a href="/" class="brand" aria-label="Kalā Atlas home"><span class="brand-symbol">${icon('flower-2')}</span><span class="brand-word">kalā<span class="brand-atlas">atlas</span></span><span class="brand-divider"></span><span class="brand-caption">A JOURNEY THROUGH<br>INDIAN ART</span></a><nav aria-label="Main navigation"><button class="nav-link active" data-nav="explore">Explore the map</button><button class="nav-link" data-nav="traditions">Art traditions</button><button class="nav-link" data-nav="timeline">Timeline</button><button class="nav-link" data-nav="about">About the atlas</button></nav><button class="saved-button" id="saved-toggle">${icon('bookmark')}<span>Saved places</span><span class="saved-count">0</span></button></header>
<main><section class="intro"><div><div class="eyebrow"><span></span> MANY PLACES. ONE EXTRAORDINARY HERITAGE.</div><h1>Discover India.<br class="mobile-break"> <em>Through its art.</em></h1><p>Follow the brushstrokes, stories, and traditions that connect a nation.</p></div><div class="intro-note"><span class="note-star">✳</span><div>Every place has a story.<br><span>Let curiosity be your guide.</span></div><svg viewBox="0 0 86 45" aria-hidden="true"><path d="M4 8Q48 3 70 33M56 29l16 6-3-15"/></svg></div></section>
<section class="explorer" aria-label="Interactive art atlas"><div class="filter-bar"><label class="search-field">${icon('search')}<input id="search" type="search" placeholder="Search places, art, or artists…" aria-label="Search places, art, or artists"><kbd>/</kbd></label><div class="filter-divider"></div><div class="category-tabs" role="group" aria-label="Filter art forms">${categories.map(c=>`<button class="category-tab ${c.id==='all'?'active':''}" data-category="${c.id}" aria-pressed="${c.id==='all'}">${icon(c.icon)}<span>${c.label}</span></button>`).join('')}</div><button id="filters-button" class="icon-button extra-filter" aria-label="More filters">${icon('sliders-horizontal')}<span class="filter-dot" hidden></span></button></div>
<div class="explorer-body"><aside class="places-panel"><div class="places-heading"><div class="eyebrow small">YOUR NEXT DISCOVERY</div><h2 id="list-title">Places that tell a story</h2><div class="results-row"><span id="results-count" aria-live="polite"></span><button id="reset-filters" title="Reset all filters">Reset ${icon('rotate-ccw')}</button></div></div><div id="place-list" class="place-list"></div><div class="list-footer">${icon('compass')} A little curiosity goes a long way.</div></aside>
<div class="map-panel" id="map-panel"><div class="map-topbar"><span class="map-status"><span class="live-dot"></span> YOUR WINDOW INTO INDIA</span><div class="view-switch"><button data-view="map" class="active" aria-label="Map view" aria-pressed="true">${icon('map')}<span>Map</span></button><button data-view="grid" aria-label="Gallery view" aria-pressed="false">${icon('layout-grid')}<span>Gallery</span></button></div></div><div id="map-loading">Drawing your next discovery…</div><svg id="art-map" viewBox="0 0 1000 650" role="group" aria-label="Map of Indian art locations. Select a marker to discover its story."><defs><pattern id="map-grain" width="6" height="6" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".5" fill="#82775a" opacity=".07"/></pattern><filter id="marker-shadow"><feDropShadow dx="0" dy="2" stdDeviation="2" flood-opacity=".14"/></filter></defs><rect width="1000" height="650" fill="#f0f0e8"/><g id="map-viewport"><g id="country-layer"></g><g id="state-layer"></g><g id="geographic-labels"></g><g id="marker-layer"></g></g><rect width="1000" height="650" fill="url(#map-grain)" pointer-events="none"/></svg><div id="gallery" hidden></div><div class="compass" aria-hidden="true"><span>N</span><svg viewBox="0 0 28 40"><path d="M14 2L25 34 14 26Z" fill="#35433a"/><path d="M14 2L3 34 14 26Z" fill="#b4b9a9"/></svg></div><div id="detail-card" class="detail-card"></div><div class="map-legend"><span><b style="background:#bb7657"></b>Painting</span><span><b style="background:#b39250"></b>Architecture</span><span><b style="background:#7c8b69"></b>Folk & tribal</span><span><b style="background:#718b90"></b>Sculpture</span><span><b style="background:#91839b"></b>Modern</span></div><div class="zoom-controls"><button id="zoom-in" aria-label="Zoom in">${icon('plus')}</button><button id="zoom-out" aria-label="Zoom out">${icon('minus')}</button><span></span><button id="reset-map" aria-label="Reset map position">${icon('scan')}</button></div><div class="map-hint">${icon('mouse-pointer-2')} Pick a place. Uncover a story.</div><div class="map-credit">Illustrative boundaries · Natural Earth / GADM</div></div></div>
<div class="atlas-footnote"><div><span class="tiny-flower">${icon('flower-2')}</span> <strong>Art has no borders.</strong><span> Discover the connections that make our heritage extraordinary.</span></div><span>13 places <b>·</b> 5 art forms <b>·</b> 2,000+ years of stories</span></div></section>
<section class="discover-section"><div class="section-title"><div><div class="eyebrow small">TAKE THE SCENIC ROUTE</div><h2>A few paths to get you started</h2></div><button id="all-traditions" class="text-link">Explore art traditions ${icon('arrow-up-right')}</button></div><div class="journey-grid"><button class="journey-card" data-journey="ancient"><img src="${places[0].image}" alt="Ancient painting at Ajanta" loading="lazy"><div class="journey-overlay"><span>TIMELESS WONDERS</span><h3>Stories set in stone</h3><p>Discover the art of ancient India ${icon('arrow-up-right')}</p></div></button><button class="journey-card" data-journey="folk"><img src="${places[2].image}" alt="Colorful Madhubani fish painting" loading="lazy"><div class="journey-overlay"><span>PASSED DOWN. REIMAGINED.</span><h3>Traditions that live on</h3><p>Meet India’s living folk arts ${icon('arrow-up-right')}</p></div></button><button class="journey-card" data-journey="architecture"><img src="${places[5].image}" alt="Stone chariot at Hampi" loading="lazy"><div class="journey-overlay"><span>BUILT TO INSPIRE</span><h3>Devotion by design</h3><p>Explore extraordinary architecture ${icon('arrow-up-right')}</p></div></button></div></section>
<footer><a class="footer-brand" href="/">kalā atlas</a><p>A small atlas. An endless discovery.</p><button data-nav="about">Sources & credits ${icon('arrow-up-right')}</button><span>Made for the curious.</span></footer></main><dialog id="modal" aria-labelledby="modal-title"><button class="modal-close icon-button" aria-label="Close dialog">${icon('x')}</button><div id="modal-content"></div></dialog><div class="toast" role="status" aria-live="polite"></div>`;

function save(id){ if(state.saved.has(id)) state.saved.delete(id); else state.saved.add(id);try{localStorage.setItem('kala-saved',JSON.stringify([...state.saved]));}catch{notify('Storage unavailable. Places are saved for this session.');}render(); }
function notify(message){$('.toast').textContent=message;$('.toast').classList.add('visible');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('.toast').classList.remove('visible'),3000);}
function render(){
 const results=filtered();
 if(!results.some(p=>p.id===state.selected)) state.selected=results[0]?.id||null;
 $('#results-count').textContent=`${results.length} ${results.length===1?'place':'places'} to explore`;
 $('#list-title').textContent=state.savedOnly?'Your little collection':'Places that tell a story';
 $('.saved-count').textContent=state.saved.size;
 $('#saved-toggle').classList.toggle('active',state.savedOnly);$('#saved-toggle').setAttribute('aria-pressed',state.savedOnly);
 document.querySelectorAll('[data-category]').forEach(el=>{el.classList.toggle('active',el.dataset.category===state.category);el.setAttribute('aria-pressed',el.dataset.category===state.category)});
 $('.filter-dot').hidden=state.era==='all'&&state.region==='all';
 $('#place-list').innerHTML=results.length?results.map(p=>`<article class="place-item ${p.id===state.selected?'selected':''}"><button class="place-select" data-select="${p.id}" aria-label="Explore ${p.name}" aria-pressed="${p.id===state.selected}"><img src="${p.image}" alt="${p.caption}" loading="lazy"><div class="place-text"><span class="place-state">${p.state}</span><h3>${p.name}</h3><p>${p.tradition}</p><span class="place-era">${p.shortPeriod}</span></div></button><button class="save-place ${state.saved.has(p.id)?'is-saved':''}" data-save="${p.id}" aria-label="${state.saved.has(p.id)?'Unsave':'Save'} ${p.name}" aria-pressed="${state.saved.has(p.id)}">${icon('bookmark')}</button></article>`).join(''):`<div class="empty-state">${icon(state.savedOnly?'bookmark':'search')}<h3>${state.savedOnly?'Make room for wonder.':'No places found.'}</h3><p>${state.savedOnly?'Save a place with its bookmark, and build a collection of your own.':'Try a different search or reset your filters to explore again.'}</p><button class="primary-button" id="empty-reset">Explore all places ${icon('arrow-right')}</button></div>`;
 const selected=places.find(p=>p.id===state.selected);
 $('#detail-card').innerHTML=selected?detailCard(selected):'';
 $('#detail-card').hidden=!selected||state.view!=='map';
 $('#gallery').innerHTML=results.length?results.map(p=>`<button class="gallery-card" data-select="${p.id}"><img src="${p.image}" alt="${p.caption}" loading="lazy"><span>${p.state}</span><h3>${p.name}</h3><p>${p.tradition}</p><span class="gallery-story">Discover the story ${icon('arrow-up-right')}</span></button>`).join(''):'<div class="empty-state"><h3>No places to show</h3><p>Reset your filters to start a new journey.</p></div>';
 drawMarkers();refreshIcons();
 document.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.classList.add('image-unavailable');img.alt='Image unavailable — '+img.alt;},{once:true}));
}
function detailCard(p){return `<div class="detail-image"><img src="${p.image}" alt="${p.caption}"><span class="feature-label">${icon('sparkles')} IN THE SPOTLIGHT</span><button class="detail-dismiss" aria-label="Close place preview">${icon('x')}</button></div><div class="detail-content"><div class="detail-location">${icon('map-pin')} ${p.state}, India <button class="save-place ${state.saved.has(p.id)?'is-saved':''}" data-save="${p.id}" aria-label="${state.saved.has(p.id)?'Unsave':'Save'} ${p.name}">${icon('bookmark')}</button></div><h2>${p.name}</h2><span class="tradition-tag" style="--tag-color:${categoryOf(p).color}">${p.tradition}</span><p class="detail-description">${p.description}</p><div class="detail-period">${icon('clock-3')} ${p.shortPeriod}</div><button class="primary-button" data-story="${p.id}">Discover the story ${icon('arrow-up-right')}</button>${p.tag?`<div class="heritage-note">${icon('landmark')}${p.tag}</div>`:''}</div>`;}
function reset(){Object.assign(state,{category:'all',era:'all',region:'all',search:'',savedOnly:false,selected:'ajanta'});$('#search').value='';render();}
function select(id){state.selected=id;render();if(state.view==='grid'||matchMedia('(max-width: 700px)').matches)openStory(id);}
function setView(view){state.view=view;$('#map-panel').classList.toggle('gallery-mode',view==='grid');$('#gallery').hidden=view!=='grid';document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',b.dataset.view===view)});render();}

async function initMap(){
 try{
 const response=await fetch('/data/india.json');if(!response.ok)throw new Error('Map data unavailable');
 const india=await response.json();
 for(const f of india.features){if(geoArea(f)>2*Math.PI){const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;polys.forEach(poly=>poly.forEach(ring=>ring.reverse()));}}
 projection=geoMercator().center([82.2,22.2]).scale(1020).translate([475,340]);
 const path=geoPath(projection);
 const countries=feature(world,world.objects.countries).features.filter(f=>['356','586','156','524','064','050','104','144','004'].includes(f.id));
 $('#country-layer').innerHTML=countries.map(f=>`<path d="${path(f)}" fill="${f.id==='356'?'#ede3cc':'#e8e8da'}" stroke="#d8d9c9" stroke-width="1"/>`).join('');
 $('#state-layer').innerHTML=india.features.map((f,i)=>`<path d="${path(f)}" fill="${['#eee3cd','#ede1c9','#efe4d1','#e9dfc6','#eee5d3'][i%5]}" stroke="#cec6b0" stroke-width=".65"><title>${f.properties.name}</title></path>`).join('');
 const labels=[['PAKISTAN',68.7,28.6],['CHINA',87.3,34],['NEPAL',84.4,28.3],['BHUTAN',90.8,28],['BANGLADESH',91,23.1],['MYANMAR',95,20],['SRI LANKA',81,6.7],['I N D I A',79.5,24.7],['Arabian Sea',69.6,16.1],['Bay of Bengal',87.7,15.3]];
 $('#geographic-labels').innerHTML=labels.map(([name,lng,lat])=>{const [x,y]=projection([lng,lat]);return `<text x="${x}" y="${y}" class="${name.includes('Sea')||name.includes('Bay')?'water-label':name.includes('I N D')?'india-label':'country-label'}">${name}</text>`}).join('');
 $('#map-loading').hidden=true;drawMarkers();refreshIcons();
 }catch(err){$('#map-loading').innerHTML='The map could not load. You can still explore every place in the list. <button id="retry-map">Try again</button>';}
}
function drawMarkers(){if(!projection)return;$('#marker-layer').innerHTML=filtered().map(p=>{let [x,y]=projection(p.coords);const selected=state.selected===p.id;const color=categoryOf(p).color;let lx=0,ly=26,anchor='middle';if(p.id==='raghurajpur'){lx=-18;ly=26;anchor='end'}if(p.id==='konark'){lx=17;ly=5;anchor='start'}if(p.id==='santiniketan'){lx=16;ly=5;anchor='start'}if(p.id==='warli'){lx=-17;ly=5;anchor='end'}return `<g class="map-marker ${selected?'selected':''}" data-marker="${p.id}" transform="translate(${x},${y})" tabindex="0" role="button" aria-label="Explore ${p.name}, ${p.tradition}" aria-pressed="${selected}">${selected?'<circle class="marker-halo" r="23" fill="#a34d36" opacity=".12"/><circle r="17" fill="#fffaf3" opacity=".85"/>':''}<circle r="${selected?11:8}" fill="${selected?'#a34d36':color}" stroke="#fffcf5" stroke-width="2.5" filter="url(#marker-shadow)"/><circle r="2" fill="#fffcf5"/><text x="${lx}" y="${ly}" text-anchor="${anchor}" class="marker-label ${selected?'active':''}">${p.mapName||p.name}</text></g>`}).join('');}
function transformMap(){ $('#map-viewport').setAttribute('transform',`translate(${pan.x+500*(1-zoom)} ${pan.y+325*(1-zoom)}) scale(${zoom})`);$('#zoom-in').disabled=zoom>=2.4;$('#zoom-out').disabled=zoom<=.75; }
function changeZoom(delta){zoom=Math.max(.75,Math.min(2.4,zoom+delta));transformMap();}

function showModal(html,cls=''){lastFocus=document.activeElement;$('#modal').className=cls;$('#modal-content').innerHTML=html;$('#modal').showModal();document.body.classList.add('modal-open');refreshIcons();}
function closeModal(){ $('#modal').close();document.body.classList.remove('modal-open');lastFocus?.focus(); }
function openStory(id){const p=places.find(p=>p.id===id);showModal(`<div class="story-hero"><img src="${p.image}" alt="${p.caption}"><span>${p.caption}</span></div><div class="story-body"><div class="eyebrow small">${p.state.toUpperCase()} · ${p.region.toUpperCase()} INDIA</div><h2 id="modal-title">${p.name}</h2><div class="story-meta"><span class="tradition-tag" style="--tag-color:${categoryOf(p).color}">${p.tradition}</span><span>${icon('clock-3')}${p.period}</span></div><p class="story-lede">${p.description}</p><h3>A place in art history</h3><p>${p.story}</p><h3>The people behind the art</h3><p>${p.artists}</p><h3>Look a little closer</h3><ul class="artwork-list">${p.artworks.map(a=>`<li>${icon('sparkles')}${a}</li>`).join('')}</ul><div class="influence-box"><div class="eyebrow small">CONNECTED BY CREATIVITY</div><h3>Beyond the place</h3><p>${p.influence}</p></div><div class="story-actions"><button class="primary-button" id="story-save" data-id="${p.id}">${icon('bookmark')}${state.saved.has(p.id)?'Saved to your places':'Save this place'}</button><a class="text-link" href="${p.source}" target="_blank" rel="noopener noreferrer">${p.sourceName} ${icon('external-link')}</a></div><p class="image-credit">Image: ${p.credit}. <a href="${p.imageSource}" target="_blank" rel="noopener noreferrer">View original & licensing</a>. Images illustrate the site or tradition; not every image depicts a listed artwork.</p></div>`,'story-modal');}
function openTraditions(){showModal(`<div class="modal-body"><div class="eyebrow small">MANY WAYS OF SEEING</div><h2 id="modal-title">Find your kind of wonder.</h2><p class="modal-intro">From cave walls to contemporary studios, discover the forms that give Indian art its extraordinary range.</p><div class="tradition-grid">${categories.filter(c=>c.id!=='all').map(c=>{const list=places.filter(p=>p.category===c.id);return `<button class="tradition-choice" data-pick-category="${c.id}" style="--tradition-color:${c.color}">${icon(c.icon)}<h3>${c.label}</h3><p>${list.map(p=>p.tradition).join(' · ')}</p><span>Explore ${list.length} places ${icon('arrow-up-right')}</span></button>`}).join('')}</div><p class="muted">These categories are starting points, not boundaries. Many places bring several art forms together.</p></div>`);}
function openTimeline(){showModal(`<div class="modal-body"><div class="eyebrow small">A JOURNEY THROUGH TIME</div><h2 id="modal-title">Centuries of creativity.</h2><p class="modal-intro">Choose an era and see its stories unfold across the map. Traditions often span more than one period.</p><div class="timeline-options">${eras.filter(e=>e.id!=='all').map(e=>`<button class="timeline-option" data-pick-era="${e.id}"><span class="timeline-dot"></span><div><span class="eyebrow small">${e.range}</span><h3>${e.label}</h3><p>${places.filter(p=>p.era.includes(e.id)).map(p=>p.name).join(' · ')}</p></div>${icon('arrow-right')}</button>`).join('')}</div><button class="text-link" data-pick-era="all">Explore the whole timeline ${icon('arrow-right')}</button><p class="muted">Era boundaries are approximate, interpretive groupings. Living traditions may have much older roots; dates reflect documented works and developments.</p></div>`);}
function openFilters(){showModal(`<div class="modal-body"><div class="eyebrow small">FOLLOW YOUR CURIOSITY</div><h2 id="modal-title">Refine your journey.</h2><label class="select-label" for="era-select">Time period</label><select id="era-select">${eras.map(e=>`<option value="${e.id}" ${state.era===e.id?'selected':''}>${e.label}${e.id==='all'?'':` · ${e.range}`}</option>`).join('')}</select><label class="select-label" for="region-select">Region</label><select id="region-select">${['all','North','South','East','West','Central','Northeast'].map(r=>`<option value="${r}" ${state.region===r?'selected':''}>${r==='all'?'All regions':r+' India'}</option>`).join('')}</select><div class="filter-actions"><button class="text-link" id="clear-extra">Clear filters</button><button class="primary-button" id="apply-filters">Show places ${icon('arrow-right')}</button></div></div>`,'filter-modal');}
function openAbout(){showModal(`<div class="modal-body"><div class="eyebrow small">ART HAS A PLACE. AND A STORY.</div><h2 id="modal-title">A small atlas.<br>An endless discovery.</h2><p class="story-lede">Kalā means art. This atlas is an invitation to discover the places, people, and ideas behind India’s extraordinary creative heritage.</p><h3>Made for the curious</h3><p>Explore ${places.length} curated places through five art forms, from ancient Buddhist sculpture to living Adivasi painting traditions and twentieth-century modernism. Search by artist, place, or tradition; filter your journey; and keep a personal collection of places to revisit.</p><h3>A starting point, not the whole picture</h3><p>No small map can represent the full diversity of Indian art. These selections are an introduction, not an exhaustive survey. Art traditions cross regional and national borders. Date ranges are approximate, and some origins remain debated.</p><h3>Sources & image credits</h3><p>Each story links to further reading and its image’s original source. The atlas draws on UNESCO, museum collections, heritage organizations, and specialist writing.</p><div class="source-list">${places.map(p=>`<a href="${p.source}" target="_blank" rel="noopener noreferrer"><span>${p.name}</span>${p.sourceName}${icon('external-link')}</a>`).join('')}</div><h3>About the map & your privacy</h3><p>The map uses Natural Earth and a simplified historical GADM state dataset via GeoHacker. Boundaries are illustrative, may not reflect current administrative divisions, and are not an assertion about disputed territory. Saved places stay in this browser’s local storage; no account is needed. External image and font providers receive normal web requests when their assets load.</p></div>`);}

$('#app').addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.dataset.category){state.category=b.dataset.category;render();}
 if(b.dataset.select)select(b.dataset.select);
 if(b.dataset.save)save(b.dataset.save);
 if(b.dataset.story)openStory(b.dataset.story);
 if(b.dataset.view)setView(b.dataset.view);
 if(b.dataset.nav){if(b.dataset.nav==='explore'){reset();setView('map');$('.explorer').scrollIntoView({behavior:'smooth',block:'start'});}if(b.dataset.nav==='traditions')openTraditions();if(b.dataset.nav==='timeline')openTimeline();if(b.dataset.nav==='about')openAbout();}
 if(b.dataset.pickCategory){state.category=b.dataset.pickCategory;closeModal();render();$('.explorer').scrollIntoView({behavior:'smooth'});}
 if(b.dataset.pickEra){state.era=b.dataset.pickEra;closeModal();render();$('.explorer').scrollIntoView({behavior:'smooth'});}
 if(b.dataset.journey){reset();if(b.dataset.journey==='ancient')state.era='ancient';else state.category=b.dataset.journey;render();$('.explorer').scrollIntoView({behavior:'smooth'});}
 if(b.classList.contains('modal-close'))closeModal();
 if(b.classList.contains('detail-dismiss'))$('#detail-card').hidden=true;
 if(b.id==='saved-toggle'){state.savedOnly=!state.savedOnly;render();$('.explorer').scrollIntoView({behavior:'smooth'});}
 if(['reset-filters','empty-reset'].includes(b.id))reset();
 if(b.id==='all-traditions')openTraditions();
 if(b.id==='filters-button')openFilters();
 if(b.id==='apply-filters'){state.era=$('#era-select').value;state.region=$('#region-select').value;closeModal();render();}
 if(b.id==='clear-extra'){$('#era-select').value='all';$('#region-select').value='all';}
 if(b.id==='story-save'){save(b.dataset.id);b.innerHTML=`${icon('bookmark')}${state.saved.has(b.dataset.id)?'Saved to your places':'Save this place'}`;refreshIcons();}
 if(b.id==='zoom-in')changeZoom(.2);
 if(b.id==='zoom-out')changeZoom(-.2);
 if(b.id==='reset-map'){zoom=1;pan={x:0,y:0};transformMap();}
 if(b.id==='retry-map')initMap();
});
$('#search').addEventListener('input',e=>{state.search=e.target.value;render();});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const rect=$('#modal').getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)closeModal();}});
$('#modal').addEventListener('cancel',e=>{e.preventDefault();closeModal();});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)&&!$('#modal').open){e.preventDefault();$('#search').focus();}});
$('#art-map').addEventListener('click',e=>{const marker=e.target.closest('[data-marker]');if(marker&&!moved)select(marker.dataset.marker);});
$('#art-map').addEventListener('keydown',e=>{const marker=e.target.closest('[data-marker]');if(marker&&['Enter',' '].includes(e.key)){e.preventDefault();select(marker.dataset.marker);}});
$('#art-map').addEventListener('pointerdown',e=>{if(e.target.closest('[data-marker]'))return;drag={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};moved=false;$('#art-map').setPointerCapture(e.pointerId);});
$('#art-map').addEventListener('pointermove',e=>{if(!drag)return;const factor=1000/$('#art-map').getBoundingClientRect().width;pan.x=drag.px+(e.clientX-drag.x)*factor;pan.y=drag.py+(e.clientY-drag.y)*factor;if(Math.abs(e.clientX-drag.x)+Math.abs(e.clientY-drag.y)>5)moved=true;transformMap();});
$('#art-map').addEventListener('pointerup',()=>{drag=null;setTimeout(()=>moved=false,0);});
$('#art-map').addEventListener('pointercancel',()=>{drag=null;moved=false;});
render();initMap();
